#!/usr/bin/env python3
"""Regenerate src/game/notes/embedded.rs from the assets/ directory.

Usage:
    python3 scripts/generate_embedded.py > src/game/notes/embedded.rs
"""
import os

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS_DIR = os.path.join(REPO_ROOT, "assets")

ogg = sorted(f for f in os.listdir(ASSETS_DIR) if f.endswith(".ogg"))

lines = [
    "// Auto-generated by script: src/game/notes/embedded.rs",
    "// Embeds the note sound assets from assets/ into the binary so piano-rs",
    "// works from any directory without the assets folder on disk.",
    "//",
    "// Regenerate with:",
    "//   python3 scripts/generate_embedded.py > src/game/notes/embedded.rs",
    "",
    "pub fn get(key: &str) -> Option<&'static [u8]> {",
    "    match key {",
]
for f in ogg:
    key = f[:-4]  # strip .ogg
    lines.append(f'        "{key}" => Some(include_bytes!("../../../assets/{f}")),')
lines += ["        _ => None,", "    }", "}", ""]

print("\n".join(lines))
